default_stages: [pre-commit]
default_install_hook_types: [pre-commit, pre-push]

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.10
  hooks:
    - id: ruff-check
      args: ['--fix', '--config', 'pyproject.toml']

- repo: https://github.com/psf/black
  rev: 26.3.1
  hooks:
    - id: black
      language_version: python3.10
      args: ['--config', 'pyproject.toml']
      verbose: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb', '2000']
      exclude: |
        (?x)^(
          .*pixi\.lock$
        )$

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.12
  hooks:
    - id: actionlint
      args:
        - "-ignore=shellcheck.*info"
