# .travis.yml

language: python

python:
  - 3.7

cache: pip

install:
  - pip install -r requirements.txt
  - pip install coverage==4.3
  - pip install pytest-cov
  - pip install codeclimate-test-reporter
  - pip install .

script:
  - flake8
  - pytest
  - coverage run -m pytest

after_success:
  - codeclimate-test-reporter
