# Copyright 2019 by Jiuguang Wang (www.robo.guru)
# All rights reserved.
# This file is part of Agenoria and is released under the MIT License.
# Please see the LICENSE file that should have been included as part of
# this package.

name: Agenoria CI

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
      PREFIX_DEV_TOKEN:
        required: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.67.0
        cache: true
        environments: default
        auth-host: prefix.dev
        auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
    - name: Install dependencies
      run: pixi install
    - name: Run lint
      run: pixi run lint
    - name: Run tests with coverage
      run: pixi run test-cov
    - name: Generate PDFs
      run: |
        rm -rf build
        pixi run plot-all
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
